### ISSUE TITLE
User Customized Directory 

### ISSUE THREAD

**Issue by Millesant** [artbits/quickio#2]
Would you like to implement a way for the user to be able to choose where the file will be? The tests I did took me a while to find the folder and I came across a number of folders within folders

![Screenshot_2023-01-08-16-02-00-102-edit_com termux](https://user-images.githubusercontent.com/76278156/211214187-f6faa4df-f865-4766-bcee-11ac2f63a5e1.jpg)

I don't know if this fits into an issue but I think it would help a lot if implemented

**Comment by Millesant** [comment]
I did some more tests and this gigantic folder creation disappeared

**Comment by artbits** [comment]
I think your suggestion is feasible. Because the core functions in development will involve the bottom directory, QuickIO temporarily manages the data directory uniformly. The custom directory function will be added later, but it will take a little time.

In the current version, QuickIO only needs to name the data folder, and it will automatically create a data directory with the specified name under the ``data/db``, ``data/kv``, and ``data/can`` directories.

**For example:** ``data/db/StoredData``, ``data/kv/StoredData``

**My little question:** How did you make that gigantic directory disappear?🤣

**Comment by Millesant** [comment]
> I think your suggestion is feasible. Because the core functions in development will involve the bottom directory, QuickIO temporarily manages the data directory uniformly. The custom directory function will be added later, but it will take a little time.
> 
> In the current version, QuickIO only needs to name the data folder, and it will automatically create a data directory with the specified name under the `data/db`, `data/kv`, and `data/can` directories.
> 
> **For example:** `data/db/StoredData`, `data/kv/StoredData`
> 
> **My little question:** How did you make that gigantic directory disappear?🤣

I honestly don't know 😅, I just deleted the folders and renamed in the `new QuickIO.KV("<name-here>");` on my Java File like in the example given here in the repository and it worked fine

I'll see if I can reproduce the same problem again

**Comment by artbits** [comment]
I think again that it is a dangerous operation for users to completely customize the data directory, but users can customize the basic directory path.

**Cause:** If the user accidentally uses ``new QuickIO.DB("xxx/yyy/zzz/data")`` and ``new QuickIO.KV("xxx/yyy/zzz/data")`` at the same time, the data files of DB and KV will be mixed in the same folder, and the two database files will be damaged. This dangerous operation should be handed over to the computer.

**Solution:** The user defines the basic directory path, and the data files are managed by QuickIO.

**For example:** ``<custom-base-path>/data/db/<db-name>`` or ``<custom-base-path>/data/kv/<kv-name>``

**Comment by Millesant** [comment]
> I think again that it is a dangerous operation for users to completely customize the data directory, but users can customize the basic directory path.
> 
> **Cause:** If the user accidentally uses `new QuickIO.DB("xxx/yyy/zzz/data")` and `new QuickIO.KV("xxx/yyy/zzz/data")` at the same time, the data files of DB and KV will be mixed in the same folder, and the two database files will be damaged. This dangerous operation should be handed over to the computer.
> 
> **Solution:** The user defines the basic directory path, and the data files are managed by QuickIO.
> 
> **For example:** `<custom-base-path>/data/db/<db-name>` or `<custom-base-path>/data/kv/<kv-name>`

I understand, I'm testing and there are some another errors going on with me, I will close this issue and if I continue with the other problems that I mentioned now I will open another one, but anyway, thank you very much friend 🙌

**Comment by artbits** [comment]
```java
//Customize parameters of DB, KV and Can.
//Custom DB parameters.
QuickIO.DB db = new QuickIO.DB(options -> options
        .name("sample_db")              //DB name.
        .basePath("/usr/qio")           //Base directory path of custom DB storage.
        .cacheSize(16L * 1024 *1024));  //Custom DB cache size, 16MB.

//Custom KV parameters.
QuickIO.KV kv = new QuickIO.KV(options -> options
        .name("sample_kv")              //KV name.
        .basePath("/usr/qio")           //Base directory path of custom KV storage.
        .cacheSize(16L * 1024 *1024));  //Custom KV cache size, 16MB.

//Custom Can parameters.
QuickIO.Can can = new QuickIO.Can(options -> options
        .name("sample_can")              //Can name.
        .basePath("/usr/qio"));          //Base directory path of custom Can storage.
```

**Comment by Millesant** [comment]
Oooh, I'll try it out as soon as I'm free from work

**Comment by Millesant** [comment]
Ok, I manage to leave the data folder where I want it in a magnificent way, but now it is giving me another exception, I will reopen this issue

**Comment by Millesant** [comment]
The exception that occurred:

![Screenshot_2023-01-26-10-13-57-675_com termux](https://user-images.githubusercontent.com/76278156/214845529-b8fb4e38-fce3-400f-8b37-3451ae08b946.png)

My code:
![Screenshot_2023-01-26-10-17-12-751_com termux](https://user-images.githubusercontent.com/76278156/214845551-d5b8d4a4-f128-448f-9d26-a3ae1ca0a938.png)

**Comment by artbits** [comment]
Line 28 of your code, _data_ is a DB object. It's not a Java bean. You can't print it out using the printJson method. Hahaha, be careful.

**Comment by Millesant** [comment]
oh sorry friend, lack of attention. I went to test since the update came out and I ended up making a mistake

**Comment by artbits** [comment]
> oh sorry friend, lack of attention. I went to test since the update came out and I ended up making a mistake 

The ability to customize the base directory path should work.
