### ISSUE TITLE
Hessian can't find Java bean 

### ISSUE THREAD

**Issue by Millesant** [artbits/quickio#3]
This problem has already been reported by what I've seen here #1, but in mine I don't modify the directory at any time, the only thing I do is create a `QuickIO.DB` ( Well that's what I believe, could I be wrong? Perhaps )

### 1 - Problem
![Screenshot_2023-01-10-20-28-31-112_com termux](https://user-images.githubusercontent.com/76278156/211685130-a921c589-e3de-4d3d-9e69-1a2d360c1dea.png)

### 2 - The Java Bean
![Screenshot_2023-01-10-20-29-18-648-edit_com termux](https://user-images.githubusercontent.com/76278156/211685146-44e63e2a-d864-4a90-8238-39eb9c85f8f3.jpg)

### 3 - Where do I create the DB
![Screenshot_2023-01-10-20-29-39-876-edit_com termux](https://user-images.githubusercontent.com/76278156/211685161-47418933-2f93-41f2-9d6c-df816e720aab.jpg)

I program on my cell phone using Termux so I don't know if this can influence something

**Comment by Millesant** [comment]
> This problem has already been reported by what I've seen here #1, but in mine I don't modify the directory at any time, the only thing I do is create a `QuickIO.DB` ( Well that's what I believe, could I be wrong? Perhaps )
> 
> ### 1 - Problem
> ![Screenshot_2023-01-10-20-28-31-112_com termux](https://user-images.githubusercontent.com/76278156/211685130-a921c589-e3de-4d3d-9e69-1a2d360c1dea.png)
> 
> ### 2 - The Java Bean
> ![Screenshot_2023-01-10-20-29-18-648-edit_com termux](https://user-images.githubusercontent.com/76278156/211685146-44e63e2a-d864-4a90-8238-39eb9c85f8f3.jpg)
> 
> ### 3 - Where do I create the DB
> ![Screenshot_2023-01-10-20-29-39-876-edit_com termux](https://user-images.githubusercontent.com/76278156/211685161-47418933-2f93-41f2-9d6c-df816e720aab.jpg)
> 
> I program on my cell phone using Termux so I don't know if this can influence something

I made another project, this time only with the dependency and then, it worked amazingly, so the software I use is probably causing this problem.

**Comment by artbits** [comment]
I followed your code, wrote it with IDEA and ran it, and found that Hessian worked normally. However, my IDEA version is relatively high, which causes Lombok to not work properly. The location of the cause of the problem cannot be determined temporarily.😄

**Comment by Millesant** [comment]
> I followed your code, wrote it with IDEA and ran it, and found that Hessian worked normally. However, my IDEA version is relatively high, which causes Lombok to not work properly. The location of the cause of the problem cannot be determined temporarily.😄

I see, well I'll close the issue and try to do something based on what you said now, thanks a lot again

**Comment by artbits** [comment]
> > I followed your code, wrote it with IDEA and ran it, and found that Hessian worked normally. However, my IDEA version is relatively high, which causes Lombok to not work properly. The location of the cause of the problem cannot be determined temporarily.😄
> 
> I see, well I'll close the issue and try to do something based on what you said now, thanks a lot again

You are welcome.
