### ISSUE TITLE
Thanks  author，Just write it down because I'm using it。

### ISSUE THREAD

**Issue by jiekey** [artbits/quickio#4]
Thanks  author，Just write it down because I'm using it，hah。

**Comment by artbits** [comment]
Thank you for your support and use.

I'm glad to hear that you are using QuickIO.

If you have any questions or suggestions, please feel free to tell me.

By New Bing.

**Comment by huiqiangyang** [comment]
非常棒我也在使用它

**Comment by artbits** [comment]
> 非常棒我也在使用它

感谢支持！我希望它可以给大家带来更多的惊喜。
