### ISSUE TITLE
maven 仓库里没有最新版的

### ISSUE THREAD

**Issue by stardustman** [artbits/quickio#6]

**Comment by artbits** [comment]
maven下载正常，你参考下图配置再尝试一下。

![32dfa4827710317272e792c753c1f586](https://github.com/artbits/quickio/assets/40884430/ee31e4cd-e639-4021-af7d-9ff325cb7401)

**Comment by stardustman** [comment]
可以了。之前没有加上 repository，加上之后下载成功了。谢谢。
```xml
    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://www.jitpack.io</url>
        </repository>
    </repositories>
```
只可以使用这个 repo 下载么？

**Comment by artbits** [comment]
是的，目前只支持这个repo。因为代码是发布到 jitpack 平台托管下载，虽然和 maven 中央仓库相似，但有点区别。

**Comment by stardustman** [comment]
好的。多谢了。
